/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SubscriptionInterface extends ethers.utils.Interface {
  functions: {
    "buy(uint8)": FunctionFragment;
    "getDuration(uint8)": FunctionFragment;
    "getEndAt(address)": FunctionFragment;
    "getIsFreeCouponUsed(address)": FunctionFragment;
    "getPrice(uint8)": FunctionFragment;
    "setEndAt(address,uint256)": FunctionFragment;
    "setIsFreeCouponUsed(address,bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getEndAt", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getIsFreeCouponUsed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEndAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIsFreeCouponUsed",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEndAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIsFreeCouponUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEndAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIsFreeCouponUsed",
    data: BytesLike
  ): Result;

  events: {};
}

export class Subscription extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SubscriptionInterface;

  functions: {
    buy(
      _plan: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDuration(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEndAt(_user: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getIsFreeCouponUsed(
      _user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getPrice(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setEndAt(
      _user: string,
      _endAt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setIsFreeCouponUsed(
      _user: string,
      _change: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buy(
    _plan: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDuration(
    _plan: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEndAt(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

  getIsFreeCouponUsed(
    _user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getPrice(_plan: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  setEndAt(
    _user: string,
    _endAt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setIsFreeCouponUsed(
    _user: string,
    _change: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buy(_plan: BigNumberish, overrides?: CallOverrides): Promise<void>;

    getDuration(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndAt(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getIsFreeCouponUsed(
      _user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getPrice(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setEndAt(
      _user: string,
      _endAt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setIsFreeCouponUsed(
      _user: string,
      _change: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    buy(
      _plan: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDuration(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndAt(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getIsFreeCouponUsed(
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setEndAt(
      _user: string,
      _endAt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setIsFreeCouponUsed(
      _user: string,
      _change: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buy(
      _plan: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDuration(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEndAt(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsFreeCouponUsed(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      _plan: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setEndAt(
      _user: string,
      _endAt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setIsFreeCouponUsed(
      _user: string,
      _change: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
