export const ActionTypes = {
	/* 유저 */
	USER_DATA_REQUEST: "USER_DATA_REQUEST",
	USER_CREATE_SUCCESS: "USER_CREATE_SUCCESS",
	USER_READ_SUCCESS: "USER_READ_SUCCESS",
	USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
	USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
	USER_DATA_FAIL: "USER_DATA_FAIL",

	/* 아티스트 */
	SELECTED_ARTIST: "SELECTED_ARTIST",
	REMOVE_SELECTED_ARTIST: "REMOVE_SELECTED_ARTIST",

	ARTIST_DATA_REQUEST: "ARTIST_DATA_REQUEST",
	ARTIST_CREATE_SUCCESS: "ARTIST_CREATE_SUCCESS",
	ARTIST_READ_SUCCESS: "ARTIST_READ_SUCCESS",
	ARTIST_UPDATE_SUCCESS: "ARTIST_UPDATE_SUCCESS",
	ARTIST_DELETE_SUCCESS: "ARTIST_DELETE_SUCCESS",
	ARTIST_DATA_FAIL: "ARTIST_DATA_FAIL",

	ARTIST_LIST_REQUEST: "ARTIST_LIST_REQUEST",
	ARTIST_LIST_CREATE_SUCCESS: "ARTIST_LIST_CREATE_SUCCESS",
	ARTIST_LIST_READ_SUCCESS: "ARTIST_LIST_READ_SUCCESS",
	ARTIST_LIST_UPDATE_SUCCESS: "ARTIST_LIST_UPDATE_SUCCESS",
	ARTIST_LIST_DELETE_SUCCESS: "ARTIST_LIST_DELETE_SUCCESS",
	ARTIST_LIST_FAIL: "ARTIST_LIST_FAIL",

	/* 아티스트 좋아요 */
	LIKE_ARTIST_REQUEST: "LIKE_ARTIST_REQUEST",
	LIKE_ARTIST_SUCCESS: "LIKE_ARTIST_SUCCESS",
	LIKE_ARTIST_FAIL: "LIKE_ARTIST_FAIL",

	/* 뮤직 */
	SELECTED_MUSIC: "SELECTED_MUSIC",
	REMOVE_SELECTED_MUSIC: "REMOVE_SELECTED_MUSIC",

  MUSIC_DATA_REQUEST: "MUSIC_DATA_REQUEST",
	MUSIC_CREATE_SUCCESS: "MUSIC_CREATE_SUCCESS",
	MUSIC_READ_SUCCESS: "MUSIC_READ_SUCCESS",
	MUSIC_UPDATE_SUCCESS: "MUSIC_UPDATE_SUCCESS",
	MUSIC_DELETE_SUCCESS: "MUSIC_DELETE_SUCCESS",
	MUSIC_DATA_FAIL: "MUSIC_DATA_FAIL",

	MUSIC_LIST_REQUEST: "MUSIC_LIST_REQUEST",
	MUSIC_LIST_SUCCESS: "MUSIC_LIST_SUCCESS",
	MUSIC_LIST_FAIL: "MUSIC_LIST_FAIL",

	/* 뮤직 좋아요 */
	LIKE_MUSIC_REQUEST: "LIKE_MUSIC_REQUEST",
	LIKE_MUSIC_SUCCESS: "LIKE_MUSIC_SUCCESS",
	LIKE_MUSIC_FAIL: "LIKE_MUSIC_FAIL",

	/* 메타마스크 */
	METAMASK_DATA_REQUEST: "METAMASK_DATA_REQUEST",
	METAMASK_DATA_SUCCESS: "METAMASK_DATA_SUCCESS",
	METAMASK_DATA_FAIL: "METAMASK_DATA_FAIL",
};