export const ActionTypes = {
  USER_DATA_REQUEST : "USER_DATA_REQUEST",
  USER_DATA_SUCCESS : "USER_DATA_SUCCESS",
  USER_DATA_FAIL : "USER_DATA_FAIL",

  ARTIST_DATA_REQUEST : "ARTIST_DATA_REQUEST",
  ARTIST_DATA_SUCCESS : "ARTIST_DATA_SUCCESS",
  ARTIST_DATA_FAIL : "ARTIST_DATA_FAIL",

  MUSIC_DATA_REQUEST : "MUSIC_DATA_REQUEST",
  MUSIC_DATA_SUCCESS : "MUSIC_DATA_SUCCESS",
  MUSIC_DATA_FAIL : "MUSIC_DATA_FAIL",

  METAMASK_DATA_REQUEST : "METAMASK_DATA_REQUEST",
  METAMASK_DATA_SUCCESS : "METAMASK_DATA_SUCCESS",
  METAMASK_DATA_FAIL : "METAMASK_DATA_FAIL",
}