export const ActionTypes = {
  /* 유저 */
  USER_DATA_REQUEST : "USER_DATA_REQUEST",
  USER_DATA_SUCCESS : "USER_DATA_SUCCESS",
  USER_DATA_FAIL : "USER_DATA_FAIL",
  
  /* 아티스트 */
  SELECTED_ARTIST : "SELECTED_ARTIST",
  REMOVE_SELECTED_ARTIST : "REMOVE_SELECTED_ARTIST",

  ARTIST_DATA_REQUEST : "ARTIST_DATA_REQUEST",
  ARTIST_DATA_SUCCESS : "ARTIST_DATA_SUCCESS",
  ARTIST_DATA_FAIL : "ARTIST_DATA_FAIL",

  ARTIST_LIST_REQUEST : "ARTIST_LIST_REQUEST",
  ARTIST_LIST_SUCCESS : "ARTIST_LIST_SUCCESS",
  ARTIST_LIST_FAIL : "ARTIST_LIST_FAIL",

  /* 뮤직 */
  SELECTED_MUSIC : "SELECTED_MUSIC",
  REMOVE_SELECTED_MUSIC : "REMOVE_SELECTED_MUSIC",

  MUSIC_LIST_REQUEST : "MUSIC_LIST_REQUEST",
  MUSIC_LIST_SUCCESS : "MUSIC_LIST_SUCCESS",
  MUSIC_LIST_FAIL : "MUSIC_LIST_FAIL",

  /* 메타마스크 */
  METAMASK_DATA_REQUEST : "METAMASK_DATA_REQUEST",
  METAMASK_DATA_SUCCESS : "METAMASK_DATA_SUCCESS",
  METAMASK_DATA_FAIL : "METAMASK_DATA_FAIL",
}