import { FormControl, InputLabel, MenuItem, Select } from "@mui/material";
import React from "react";
import "./ListenerType.css";
const CountryType = ({ setSelected }) => {
  const onChangeCountry = (e) => {
    setSelected(e.target.value);
  };

  return (
    <div className="music-type-container">
      <FormControl>
        <Select
          className="country"
          country="my-country"
          onChange={onChangeCountry}
          defaultValue="KS"
        >
          <MenuItem value="AF">Afghanistan</MenuItem>
          <MenuItem value="AL">Albania</MenuItem>
          <MenuItem value="Algeria">Algeria</MenuItem>
          <MenuItem value="AS">American Samoa</MenuItem>
          <MenuItem value="Andorra">Andorra</MenuItem>
          <MenuItem value="AG">Angola</MenuItem>
          <MenuItem value="AI">Anguilla</MenuItem>
          <MenuItem value="AG">Antigua &amp; Barbuda</MenuItem>
          <MenuItem value="AR">Argentina</MenuItem>
          <MenuItem value="AA">Armenia</MenuItem>
          <MenuItem value="AW">Aruba</MenuItem>
          <MenuItem value="AU">Australia</MenuItem>
          <MenuItem value="AT">Austria</MenuItem>
          <MenuItem value="AZ">Azerbaijan</MenuItem>
          <MenuItem value="BS">Bahamas</MenuItem>
          <MenuItem value="BH">Bahrain</MenuItem>
          <MenuItem value="BD">Bangladesh</MenuItem>
          <MenuItem value="BB">Barbados</MenuItem>
          <MenuItem value="BY">Belarus</MenuItem>
          <MenuItem value="BE">Belgium</MenuItem>
          <MenuItem value="BZ">Belize</MenuItem>
          <MenuItem value="BJ">Benin</MenuItem>
          <MenuItem value="BM">Bermuda</MenuItem>
          <MenuItem value="BT">Bhutan</MenuItem>
          <MenuItem value="BO">Bolivia</MenuItem>
          <MenuItem value="BL">Bonaire</MenuItem>
          <MenuItem value="BA">Bosnia &amp; Herzegovina</MenuItem>
          <MenuItem value="BW">Botswana</MenuItem>
          <MenuItem value="BR">Brazil</MenuItem>
          <MenuItem value="BC">British Indian Ocean Ter</MenuItem>
          <MenuItem value="BN">Brunei</MenuItem>
          <MenuItem value="BG">Bulgaria</MenuItem>
          <MenuItem value="BF">Burkina Faso</MenuItem>
          <MenuItem value="BI">Burundi</MenuItem>
          <MenuItem value="KH">Cambodia</MenuItem>
          <MenuItem value="CM">Cameroon</MenuItem>
          <MenuItem value="CA">Canada</MenuItem>
          <MenuItem value="IC">Canary Islands</MenuItem>
          <MenuItem value="CV">Cape Verde</MenuItem>
          <MenuItem value="KY">Cayman Islands</MenuItem>
          <MenuItem value="CF">Central African Republic</MenuItem>
          <MenuItem value="TD">Chad</MenuItem>
          <MenuItem value="CD">Channel Islands</MenuItem>
          <MenuItem value="CL">Chile</MenuItem>
          <MenuItem value="CN">China</MenuItem>
          <MenuItem value="CI">Christmas Island</MenuItem>
          <MenuItem value="CS">Cocos Island</MenuItem>
          <MenuItem value="CO">Colombia</MenuItem>
          <MenuItem value="CC">Comoros</MenuItem>
          <MenuItem value="CG">Congo</MenuItem>
          <MenuItem value="CK">Cook Islands</MenuItem>
          <MenuItem value="CR">Costa Rica</MenuItem>
          <MenuItem value="CT">Cote D'Ivoire</MenuItem>
          <MenuItem value="HR">Croatia</MenuItem>
          <MenuItem value="CU">Cuba</MenuItem>
          <MenuItem value="CB">Curacao</MenuItem>
          <MenuItem value="CY">Cyprus</MenuItem>
          <MenuItem value="CZ">Czech Republic</MenuItem>
          <MenuItem value="DK">Denmark</MenuItem>
          <MenuItem value="DJ">Djibouti</MenuItem>
          <MenuItem value="DM">Dominica</MenuItem>
          <MenuItem value="DO">Dominican Republic</MenuItem>
          <MenuItem value="TM">East Timor</MenuItem>
          <MenuItem value="EC">Ecuador</MenuItem>
          <MenuItem value="EG">Egypt</MenuItem>
          <MenuItem value="SV">El Salvador</MenuItem>
          <MenuItem value="GQ">Equatorial Guinea</MenuItem>
          <MenuItem value="ER">Eritrea</MenuItem>
          <MenuItem value="EE">Estonia</MenuItem>
          <MenuItem value="ET">Ethiopia</MenuItem>
          <MenuItem value="FA">Falkland Islands</MenuItem>
          <MenuItem value="FO">Faroe Islands</MenuItem>
          <MenuItem value="FJ">Fiji</MenuItem>
          <MenuItem value="FI">Finland</MenuItem>
          <MenuItem value="FR">France</MenuItem>
          <MenuItem value="GF">French Guiana</MenuItem>
          <MenuItem value="PF">French Polynesia</MenuItem>
          <MenuItem value="FS">French Southern Ter</MenuItem>
          <MenuItem value="GA">Gabon</MenuItem>
          <MenuItem value="GM">Gambia</MenuItem>
          <MenuItem value="GE">Georgia</MenuItem>
          <MenuItem value="DE">Germany</MenuItem>
          <MenuItem value="GH">Ghana</MenuItem>
          <MenuItem value="GI">Gibraltar</MenuItem>
          <MenuItem value="GB">Great Britain</MenuItem>
          <MenuItem value="GR">Greece</MenuItem>
          <MenuItem value="GL">Greenland</MenuItem>
          <MenuItem value="GD">Grenada</MenuItem>
          <MenuItem value="GP">Guadeloupe</MenuItem>
          <MenuItem value="GU">Guam</MenuItem>
          <MenuItem value="GT">Guatemala</MenuItem>
          <MenuItem value="GN">Guinea</MenuItem>
          <MenuItem value="GY">Guyana</MenuItem>
          <MenuItem value="HT">Haiti</MenuItem>
          <MenuItem value="HW">Hawaii</MenuItem>
          <MenuItem value="HN">Honduras</MenuItem>
          <MenuItem value="HK">Hong Kong</MenuItem>
          <MenuItem value="HU">Hungary</MenuItem>
          <MenuItem value="IS">Iceland</MenuItem>
          <MenuItem value="IN">India</MenuItem>
          <MenuItem value="ID">Indonesia</MenuItem>
          <MenuItem value="IA">Iran</MenuItem>
          <MenuItem value="IQ">Iraq</MenuItem>
          <MenuItem value="IR">Ireland</MenuItem>
          <MenuItem value="IM">Isle of Man</MenuItem>
          <MenuItem value="IL">Israel</MenuItem>
          <MenuItem value="IT">Italy</MenuItem>
          <MenuItem value="JM">Jamaica</MenuItem>
          <MenuItem value="JP">Japan</MenuItem>
          <MenuItem value="JO">Jordan</MenuItem>
          <MenuItem value="KZ">Kazakhstan</MenuItem>
          <MenuItem value="KE">Kenya</MenuItem>
          <MenuItem value="KI">Kiribati</MenuItem>
          <MenuItem value="NK">Korea North</MenuItem>
          <MenuItem value="KS">Korea South</MenuItem>
          <MenuItem value="KW">Kuwait</MenuItem>
          <MenuItem value="KG">Kyrgyzstan</MenuItem>
          <MenuItem value="LA">Laos</MenuItem>
          <MenuItem value="LV">Latvia</MenuItem>
          <MenuItem value="LB">Lebanon</MenuItem>
          <MenuItem value="LS">Lesotho</MenuItem>
          <MenuItem value="LR">Liberia</MenuItem>
          <MenuItem value="LY">Libya</MenuItem>
          <MenuItem value="LI">Liechtenstein</MenuItem>
          <MenuItem value="LT">Lithuania</MenuItem>
          <MenuItem value="LU">Luxembourg</MenuItem>
          <MenuItem value="MO">Macau</MenuItem>
          <MenuItem value="MK">Macedonia</MenuItem>
          <MenuItem value="MG">Madagascar</MenuItem>
          <MenuItem value="MY">Malaysia</MenuItem>
          <MenuItem value="MW">Malawi</MenuItem>
          <MenuItem value="MV">Maldives</MenuItem>
          <MenuItem value="ML">Mali</MenuItem>
          <MenuItem value="MT">Malta</MenuItem>
          <MenuItem value="MH">Marshall Islands</MenuItem>
          <MenuItem value="MQ">Martinique</MenuItem>
          <MenuItem value="MR">Mauritania</MenuItem>
          <MenuItem value="MU">Mauritius</MenuItem>
          <MenuItem value="ME">Mayotte</MenuItem>
          <MenuItem value="MX">Mexico</MenuItem>
          <MenuItem value="MI">Midway Islands</MenuItem>
          <MenuItem value="MD">Moldova</MenuItem>
          <MenuItem value="MC">Monaco</MenuItem>
          <MenuItem value="MN">Mongolia</MenuItem>
          <MenuItem value="MS">Montserrat</MenuItem>
          <MenuItem value="MA">Morocco</MenuItem>
          <MenuItem value="MZ">Mozambique</MenuItem>
          <MenuItem value="MM">Myanmar</MenuItem>
          <MenuItem value="NA">Nambia</MenuItem>
          <MenuItem value="NU">Nauru</MenuItem>
          <MenuItem value="NP">Nepal</MenuItem>
          <MenuItem value="AN">Netherland Antilles</MenuItem>
          <MenuItem value="NL">Netherlands (Holland, Europe)</MenuItem>
          <MenuItem value="NV">Nevis</MenuItem>
          <MenuItem value="NC">New Caledonia</MenuItem>
          <MenuItem value="NZ">New Zealand</MenuItem>
          <MenuItem value="NI">Nicaragua</MenuItem>
          <MenuItem value="NE">Niger</MenuItem>
          <MenuItem value="NG">Nigeria</MenuItem>
          <MenuItem value="NW">Niue</MenuItem>
          <MenuItem value="NF">Norfolk Island</MenuItem>
          <MenuItem value="NO">Norway</MenuItem>
          <MenuItem value="OM">Oman</MenuItem>
          <MenuItem value="PK">Pakistan</MenuItem>
          <MenuItem value="PW">Palau Island</MenuItem>
          <MenuItem value="PS">Palestine</MenuItem>
          <MenuItem value="PA">Panama</MenuItem>
          <MenuItem value="PG">Papua New Guinea</MenuItem>
          <MenuItem value="PY">Paraguay</MenuItem>
          <MenuItem value="PE">Peru</MenuItem>
          <MenuItem value="PH">Philippines</MenuItem>
          <MenuItem value="PO">Pitcairn Island</MenuItem>
          <MenuItem value="PL">Poland</MenuItem>
          <MenuItem value="PT">Portugal</MenuItem>
          <MenuItem value="PR">Puerto Rico</MenuItem>
          <MenuItem value="QA">Qatar</MenuItem>
          <MenuItem value="ME">Republic of Montenegro</MenuItem>
          <MenuItem value="RS">Republic of Serbia</MenuItem>
          <MenuItem value="RE">Reunion</MenuItem>
          <MenuItem value="RO">Romania</MenuItem>
          <MenuItem value="RU">Russia</MenuItem>
          <MenuItem value="RW">Rwanda</MenuItem>
          <MenuItem value="NT">St Barthelemy</MenuItem>
          <MenuItem value="EU">St Eustatius</MenuItem>
          <MenuItem value="HE">St Helena</MenuItem>
          <MenuItem value="KN">St Kitts-Nevis</MenuItem>
          <MenuItem value="LC">St Lucia</MenuItem>
          <MenuItem value="MB">St Maarten</MenuItem>
          <MenuItem value="PM">St Pierre &amp; Miquelon</MenuItem>
          <MenuItem value="VC">St Vincent &amp; Grenadines</MenuItem>
          <MenuItem value="SP">Saipan</MenuItem>
          <MenuItem value="SO">Samoa</MenuItem>
          <MenuItem value="AS">Samoa American</MenuItem>
          <MenuItem value="SM">San Marino</MenuItem>
          <MenuItem value="ST">Sao Tome &amp; Principe</MenuItem>
          <MenuItem value="SA">Saudi Arabia</MenuItem>
          <MenuItem value="SN">Senegal</MenuItem>
          <MenuItem value="RS">Serbia</MenuItem>
          <MenuItem value="SC">Seychelles</MenuItem>
          <MenuItem value="SL">Sierra Leone</MenuItem>
          <MenuItem value="SG">Singapore</MenuItem>
          <MenuItem value="SK">Slovakia</MenuItem>
          <MenuItem value="SI">Slovenia</MenuItem>
          <MenuItem value="SB">Solomon Islands</MenuItem>
          <MenuItem value="OI">Somalia</MenuItem>
          <MenuItem value="ZA">South Africa</MenuItem>
          <MenuItem value="ES">Spain</MenuItem>
          <MenuItem value="LK">Sri Lanka</MenuItem>
          <MenuItem value="SD">Sudan</MenuItem>
          <MenuItem value="SR">Suriname</MenuItem>
          <MenuItem value="SZ">Swaziland</MenuItem>
          <MenuItem value="SE">Sweden</MenuItem>
          <MenuItem value="CH">Switzerland</MenuItem>
          <MenuItem value="SY">Syria</MenuItem>
          <MenuItem value="TA">Tahiti</MenuItem>
          <MenuItem value="TW">Taiwan</MenuItem>
          <MenuItem value="TJ">Tajikistan</MenuItem>
          <MenuItem value="TZ">Tanzania</MenuItem>
          <MenuItem value="TH">Thailand</MenuItem>
          <MenuItem value="TG">Togo</MenuItem>
          <MenuItem value="TK">Tokelau</MenuItem>
          <MenuItem value="TO">Tonga</MenuItem>
          <MenuItem value="TT">Trinidad &amp; Tobago</MenuItem>
          <MenuItem value="TN">Tunisia</MenuItem>
          <MenuItem value="TR">Turkey</MenuItem>
          <MenuItem value="TU">Turkmenistan</MenuItem>
          <MenuItem value="TC">Turks &amp; Caicos Is</MenuItem>
          <MenuItem value="TV">Tuvalu</MenuItem>
          <MenuItem value="UG">Uganda</MenuItem>
          <MenuItem value="UA">Ukraine</MenuItem>
          <MenuItem value="AE">United Arab Emirates</MenuItem>
          <MenuItem value="GB">United Kingdom</MenuItem>
          <MenuItem value="US">United States of America</MenuItem>
          <MenuItem value="UY">Uruguay</MenuItem>
          <MenuItem value="UZ">Uzbekistan</MenuItem>
          <MenuItem value="VU">Vanuatu</MenuItem>
          <MenuItem value="VS">Vatican City State</MenuItem>
          <MenuItem value="VE">Venezuela</MenuItem>
          <MenuItem value="VN">Vietnam</MenuItem>
          <MenuItem value="VB">Virgin Islands (Brit)</MenuItem>
          <MenuItem value="VA">Virgin Islands (USA)</MenuItem>
          <MenuItem value="WK">Wake Island</MenuItem>
          <MenuItem value="WF">Wallis &amp; Futana Is</MenuItem>
          <MenuItem value="YE">Yemen</MenuItem>
          <MenuItem value="ZR">Zaire</MenuItem>
          <MenuItem value="ZM">Zambia</MenuItem>
          <MenuItem value="ZW">Zimbabwe</MenuItem>
        </Select>
      </FormControl>
    </div>
  );
};

export default CountryType;
